name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run ESLint
        run: |
          npm run lint

      - name: Run Prettier check
        run: |
          npx prettier --check .

      - name: Run unit tests
        run: |
          ng run test:staged

  e2e-test:
    runs-on: ubuntu-latest
    needs: lint-test
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run E2E tests
        run: |
          npm run e2e-headless

  deploy-staging:
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: e2e-test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm ci

      - name: Deploy to Production
        run: |
          echo "Deploying to Production..."
